# Generated by Django 5.2.10 on 2026-03-06

from django.conf import settings
from django.db import migrations, models


def _unique_username(AuthUser, base_username):
    base_username = (base_username or '').strip()
    if not base_username:
        base_username = 'user'

    max_len = AuthUser._meta.get_field('username').max_length
    base = base_username[:max_len]
    if not AuthUser.objects.filter(username=base).exists():
        return base

    suffix = 1
    while True:
        candidate = f"{base_username}_{suffix}"
        candidate = candidate[:max_len]
        if not AuthUser.objects.filter(username=candidate).exists():
            return candidate
        suffix += 1


def link_admin_django_users(apps, schema_editor):
    Admin = apps.get_model('core_admin', 'Admin')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    AuthUser = apps.get_model(app_label, model_name)

    for admin in Admin.objects.all().order_by('id'):
        email = (admin.email or '').strip()
        if not email:
            continue

        if getattr(admin, 'django_user_id', None):
            try:
                auth_user = AuthUser.objects.filter(id=admin.django_user_id).first()
                if auth_user and admin.password and auth_user.password != admin.password:
                    auth_user.password = admin.password
                    auth_user.is_active = bool(getattr(admin, 'is_active', True))
                    auth_user.save(update_fields=['password', 'is_active'])
            except Exception:
                pass
            continue

        username = _unique_username(AuthUser, email)
        auth_user, created = AuthUser.objects.get_or_create(
            username=username,
            defaults={
                'email': email,
                'first_name': '',
                'last_name': '',
                'is_active': bool(getattr(admin, 'is_active', True)),
                'password': admin.password or '',
            },
        )

        if not created:
            changed_fields = []
            if hasattr(auth_user, 'email') and auth_user.email != email:
                auth_user.email = email
                changed_fields.append('email')
            if hasattr(auth_user, 'is_active') and auth_user.is_active != bool(getattr(admin, 'is_active', True)):
                auth_user.is_active = bool(getattr(admin, 'is_active', True))
                changed_fields.append('is_active')
            if admin.password and auth_user.password != admin.password:
                auth_user.password = admin.password
                changed_fields.append('password')
            if changed_fields:
                auth_user.save(update_fields=changed_fields)

        admin.django_user_id = auth_user.id
        admin.save(update_fields=['django_user'])


def unlink_admin_django_users(apps, schema_editor):
    Admin = apps.get_model('core_admin', 'Admin')
    Admin.objects.update(django_user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='django_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='meeva_core_admin',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(link_admin_django_users, unlink_admin_django_users),
    ]
