# Generated by Django 5.2.10 on 2026-03-06

from django.conf import settings
from django.db import migrations, models


def _unique_username(AuthUser, base_username):
    base_username = (base_username or '').strip()
    if not base_username:
        base_username = 'user'

    max_len = AuthUser._meta.get_field('username').max_length
    base = base_username[:max_len]
    if not AuthUser.objects.filter(username=base).exists():
        return base

    # Disambiguate deterministically.
    suffix = 1
    while True:
        candidate = f"{base_username}_{suffix}"
        candidate = candidate[:max_len]
        if not AuthUser.objects.filter(username=candidate).exists():
            return candidate
        suffix += 1


def link_django_users(apps, schema_editor):
    Customer = apps.get_model('users', 'User')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    AuthUser = apps.get_model(app_label, model_name)

    # Iterate in stable order for reproducibility.
    for customer in Customer.objects.all().order_by('id'):
        email = (customer.email or '').strip()
        if not email:
            continue

        if getattr(customer, 'django_user_id', None):
            # Ensure password sync (best-effort).
            try:
                auth_user = AuthUser.objects.filter(id=customer.django_user_id).first()
                if auth_user and customer.password and auth_user.password != customer.password:
                    auth_user.password = customer.password
                    auth_user.save(update_fields=['password'])
            except Exception:
                pass
            continue

        username = _unique_username(AuthUser, email)

        auth_user, created = AuthUser.objects.get_or_create(
            username=username,
            defaults={
                'email': email,
                'first_name': getattr(customer, 'first_name', '') or '',
                'last_name': getattr(customer, 'last_name', '') or '',
                'is_active': bool(getattr(customer, 'is_active', True)),
                'password': customer.password or '',
            },
        )

        if not created:
            changed_fields = []
            if hasattr(auth_user, 'email') and auth_user.email != email:
                auth_user.email = email
                changed_fields.append('email')
            if hasattr(auth_user, 'first_name') and auth_user.first_name != (customer.first_name or ''):
                auth_user.first_name = customer.first_name or ''
                changed_fields.append('first_name')
            if hasattr(auth_user, 'last_name') and auth_user.last_name != (customer.last_name or ''):
                auth_user.last_name = customer.last_name or ''
                changed_fields.append('last_name')
            if hasattr(auth_user, 'is_active') and auth_user.is_active != bool(customer.is_active):
                auth_user.is_active = bool(customer.is_active)
                changed_fields.append('is_active')
            if customer.password and auth_user.password != customer.password:
                auth_user.password = customer.password
                changed_fields.append('password')
            if changed_fields:
                auth_user.save(update_fields=changed_fields)

        customer.django_user_id = auth_user.id
        customer.save(update_fields=['django_user'])


def unlink_django_users(apps, schema_editor):
    Customer = apps.get_model('users', 'User')
    Customer.objects.update(django_user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='django_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='meeva_customer',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(link_django_users, unlink_django_users),
    ]
