# Generated by Django 5.2.10 on 2026-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wishlist'),
        ('vendor', '0007_order_order_buyer_created_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['email', 'role', 'is_verified'], name='otp_email_role_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['expires_at'], name='otp_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'added_at'], name='wishlist_user_added_idx'),
        ),
    ]
