# Generated by Django 5.2.10 on 2026-02-19 05:03

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()


def create_default_admin(apps, schema_editor):
    """Create default admin user from .env file"""
    Admin = apps.get_model('admin', 'Admin')
    
    # Get credentials from .env
    admin_email = os.getenv('ADMIN_EMAIL', 'admin@meeva.com')
    admin_password = os.getenv('ADMIN_PASSWORD', 'Admin@123')
    
    # Check if admin already exists
    if not Admin.objects.filter(email=admin_email).exists():
        Admin.objects.create(
            email=admin_email,
            password=make_password(admin_password),
            is_active=True
        )
        print(f"✅ Default admin created: {admin_email} / {admin_password}")


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin),
    ]
