# Generated by Django 5.2.10 on 2026-02-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_create_default_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
    ]
